image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv dist public  # Move the Vite build output to 'public'
  artifacts:
    paths:
      - public  # GitLab Pages requires this folder
  only:
    - main  # Deploy only when pushing to 'main'
